services:
  # PostgreSQL база данных
  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Бэкенд на Node.js
  server:
    build: ./server
    container_name: todo_server
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo_db
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  # Фронтенд на React
  client:
    build: ./client
    container_name: todo_client
    depends_on:
      - server
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:4000/api
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: